package PrimeApp;


/**
* PrimeApp/PrimeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Sunday, 28 May, 2023 5:17:08 PM IST
*/

public interface PrimeOperations 
{
  String CheckPrime (int num);
  void shutdown ();
} // interface PrimeOperations
