package StringReverseApp;


/**
* StringReverseApp/StringReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Sunday, 28 May, 2023 9:25:50 AM IST
*/

public interface StringReverseOperations 
{
  String Reverse (String str1);
  void shutdown ();
} // interface StringReverseOperations
