package StringReverseApp;


/**
* StringReverseApp/StringReverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Sunday, 28 May, 2023 9:25:50 AM IST
*/

public interface StringReverse extends StringReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringReverse
